debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.thc.winterspr: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  #
  datasource:
    
  mail:
    host: smtps.hiworks.com       # Hiworks SMTP (SSL) 서버
    port: 465                     # SSL 전용 포트
    username: william7872ksh@forhim.kr   # 반드시 풀 이메일 주소
    password: bnn3570jhk7872!!         # 실제 메일 비밀번호 (앱 전용 비밀번호)
    protocol: smtp                # SMTP 프로토콜
    properties:
      mail:
        smtp:
          auth: true              # 인증 사용
          ssl:
            enable: true          # SSL 사용
          starttls:
            enable: false         # STARTTLS 비활성 (포트 465은 SSL 전용)


  #
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    #hibernate.ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
      hibernate.jdbc.time_zone: Asia/Seoul
  thymeleaf:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    remote:
      restart:
        enabled: false
  freemarker:
    cache: false
  sql.init.mode: always
  #sql.init.mode: never

springdoc:
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha

external:
    
mybatis:
  type-aliases-package: com.example.yellowaution.domain
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true




